version: "3.9"
services:

  development:

    # Build from source
    build:
      context: .
      args:
        - ENV=development

    # Publish port
    ports:
      - "5000:5000"

    # Bind records and src directories
    volumes:
      - "./records:/home/a2j/records"
      - "./src:/home/a2j/src"

  production:

    # Run from image
    image: deasilsoft/a2j

    # Bind records directory
    volumes:
      - "./records:/home/a2j/records"

    # Always restart container on Docker start
    restart: always
