version: "3.9"
services:

  development:

    # Build from source
    build: .

    # Set environment variables
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

    # Publish port
    ports:
      - "5000:5000"

    # Bind records & src directories
    volumes:
      - "./records:/home/a2j/records"
      - "./src:/home/a2j/src"

  production:

    # Run from image
    image: deasilsoft/a2j

    # Set environment variables
    environment:
      - FLASK_ENV=production

    # Bind records directory
    volumes:
      - "./records:/home/a2j/records"

    # Always restart container on Docker start
    restart: always
