name: Build and Push a2j to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  main:
    environment: DOCKER
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set Up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build And Push To Latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: deasilsoft/a2j:latest

      - name: Latest Image Digest
        run: echo ${{ steps.docker_build_latest.outputs.digest }}

      - name: Read VERSION
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: Build And Push To Version
        id: docker_build_version
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: deasilsoft/a2j:${{ steps.version.outputs.content }}

      - name: Latest Image Digest
        run: echo ${{ steps.docker_build_version.outputs.digest }}
