name: ao2record-to-json
on: [ push ]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Image
        run: docker build -t deasilsoft/a2j .
      - name: Run Container
        run: docker run -d --name a2j deasilsoft/a2j
      - name: Install Test Environment
        run: |
          docker exec a2j apk --no-cache add curl
          docker exec a2j pip install pytest
      - name: Run Tests
        run: docker exec a2j python -m pytest
