name: ao2record-to-json
on: [ push ]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Installing docker...
        run: sudo curl -sSL https://get.docker.com/ | sh
      - name: Building image...
        run: docker build -t deasilsoft/a2j .
      - name: Running container...
        run: docker run -d --name a2j deasilsoft/a2j
      - name: Installing test environment...
        run: docker exec -d a2j apk add pytest curl
      - name: Running tests...
        run: docker exec -d a2j pytest
