name: ao2record-to-json
on: [ push ]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build & Run Container
        run: docker-compose up --build -d
      - name: Install Test Environment
        run: |
          docker exec a2j apk --no-cache add curl
          docker exec a2j pip install pytest
      - name: Run Tests
        run: docker exec a2j python -m pytest
