name: github_action
on: [ push ]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build & Run Container
        run: docker-compose up --build -d
      - name: Install Test Environment
        run: |
          docker exec github_action_a2j_1 apk --no-cache add curl
          docker exec github_action_a2j_1 pip install pytest
      - name: Run Tests
        run: docker exec github_action_a2j_1 python -m pytest
