name: ao2record-to-json

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Installing docker...
        run: sudo apt-get install docker
      - name: Building image...
        run: sudo docker build -t deasilsoft/a2j:latest .
      - name: Running container...
        run: sudo docker run -d deasilsoft/a2j:latest --name a2j apk add pytest
      - name: Running tests...
        run: sudo docker exec --name a2j pytest
