name: ao2record-to-json

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Installing docker...
        run: sudo curl -sSL https://get.docker.com/ | sh
      - name: Building image...
        run: docker build -t deasilsoft/a2j:latest .
      - name: Running container...
        run: docker run -d deasilsoft/a2j:latest --name a2j apk add pytest
      - name: Running tests...
        run: docker exec --name a2j pytest
