name: Run a2j Tests
on:
  push:
jobs:
  main:
    environment: CODECOV
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Build & Run Docker Container
        run: docker-compose up --build -d

      - name: Run Pytest & Coverage
        run: docker exec a2j_development_1 pytest --cov=src --cov-report=xml tests

      - name: Send Coverage Report To Codecov
        run: docker exec a2j_development_1 codecov -t ${{ secrets.CODECOV_TOKEN }}
