name: Run a2j Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "47 10 * * 5"

jobs:
  main:
    environment: CODECOV
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Build & Run Docker Container
        run: docker compose up --build -d

      - name: Run Pytest & Coverage
        run: docker compose exec -T development pytest --cov=src --cov-report=xml tests

      - name: Install Git
        run: docker compose exec -T -u 0 development apk --no-cache add git

      - name: Send Coverage Report To Codecov
        run: docker compose exec -T development codecov -t ${{ secrets.CODECOV_TOKEN }}
