name: Run a2j Tests
on:
  push:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Create Environment File (.env)
        run: cp .env.example .env

      - name: Build & Run Docker Container
        run: docker-compose up --build -d

      - name: Install & Run Pytest Inside Container
        run: |
          docker exec a2j_a2j_1 pip install pytest
          docker exec a2j_a2j_1 python -m pytest
