name: Run a2j Tests
on:
  push:
jobs:
  main:
    environment: CODECOV
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Create Environment File (.env)
        run: cp .env.example .env

      - name: Build & Run Docker Container
        run: docker-compose up --build -d

      - name: Install & Run Pytest Inside Container
        run: |
          pip install --no-cache-dir pytest pytest-cov
          pytest --cov=src tests

      - name: Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
