name: Run a2j Tests
on:
  push:
jobs:
  main:
    environment: CODECOV
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Build & Run Docker Container
        run: docker-compose up --build -d

      - name: Run Pytest & Coverage
        run: docker-compose exec development pytest --cov=src --cov-report=xml tests

      - name: Install Git
        run: docker-compose exec -u 0 development apk --no-cache add git

      - name: Send Coverage Report To Codecov
        run: docker-compose exec development codecov -t ${{ secrets.CODECOV_TOKEN }}
